# Generated by Django 3.0.3 on 2020-04-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choroby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('wiek', models.IntegerField(default=0)),
                ('plec', models.CharField(max_length=20)),
                ('student', models.CharField(max_length=4)),
                ('odpornosc_stresowa', models.IntegerField(default=0)),
                ('rozproszenie', models.IntegerField(default=0)),
                ('wynik1', models.IntegerField(default=0)),
                ('wynik2', models.IntegerField(default=0)),
                ('wynikSAR', models.IntegerField(default=0)),
                ('wiedza_o_nomofobii', models.CharField(max_length=20)),
                ('podejrzenie_nomofobii', models.CharField(max_length=20)),
                ('choroby', models.ManyToManyField(to='mainapp.Choroby')),
            ],
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=20)),
                ('przywiazanie', models.CharField(max_length=200)),
                ('przekatna', models.IntegerField(default=0)),
                ('czas_dzienne', models.IntegerField(default=0)),
                ('najczesciej', models.CharField(max_length=200)),
                ('czas_najczesciej', models.IntegerField(default=0)),
                ('cena', models.CharField(max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Uzaleznienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='person',
            name='uzaleznienia',
            field=models.ManyToManyField(to='mainapp.Uzaleznienia'),
        ),
    ]
