# Generated by Django 3.0.3 on 2020-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200426_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefon',
            name='czas_dzienne',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='czas_najczesciej',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='przekatna',
            field=models.FloatField(default=0),
        ),
    ]
